//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaAuctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int idauction { get; set; }
        public string priceup { get; set; }
        public Nullable<System.DateTime> dateauction { get; set; }
        public string timeauction { get; set; }
        public string statusauction { get; set; }
        public string statusorder { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idproduct { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
