//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaAuctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int idNotif { get; set; }
        public string titleN { get; set; }
        public string contentN { get; set; }
        public Nullable<System.DateTime> dateN { get; set; }
        public string statusNotif { get; set; }
        public Nullable<int> idproduct { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
