//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaAuctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int idorder { get; set; }
        public Nullable<System.DateTime> dateorder { get; set; }
        public string timeorder { get; set; }
        public Nullable<int> idauction { get; set; }
    
        public virtual Auction Auction { get; set; }
    }
}
