//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaAuctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int idpay { get; set; }
        public string method { get; set; }
        public string currency { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string price { get; set; }
        public string tax { get; set; }
        public string ship { get; set; }
        public string namecontact { get; set; }
        public string phonecontact { get; set; }
        public string addresscontact { get; set; }
        public string subtotal { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> idproduct { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
