//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaAuctions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Auctions = new HashSet<Auction>();
            this.Notifications = new HashSet<Notification>();
            this.Payments = new HashSet<Payment>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int idproduct { get; set; }
        public string namepro { get; set; }
        public string descriptionpro { get; set; }
        public string priceauction { get; set; }
        public string pricebuy { get; set; }
        public Nullable<System.DateTime> datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public string timestart { get; set; }
        public string timeend { get; set; }
        public string statuspro { get; set; }
        public Nullable<int> idtypepro { get; set; }
        public Nullable<int> iddespro { get; set; }
        public Nullable<int> idimgpro { get; set; }
        public Nullable<int> idUser { get; set; }

        [NotMapped]
        public HttpPostedFileBase[] upfiles { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auctions { get; set; }
        public virtual DesciptionProduct DesciptionProduct { get; set; }
        public virtual ImageProduct ImageProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
