//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaAuctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int idreviews { get; set; }
        public string contentrev { get; set; }
        public Nullable<System.DateTime> daterev { get; set; }
        public string timerev { get; set; }
        public Nullable<int> numstart { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idproduct { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
